repositoryUrl: https://github.com/gsmlg-dev/phoenix_react.git
branches:
  - main
  - next
  - next-major
  - {name: 'beta', prerelease: true}
  - {name: 'alpha', prerelease: true}
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - 'assets':
        - 'CHANGELOG.md'
        - 'mix.exs'
        - 'README.md'
      'message': 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - 'prepareCmd' : |
        echo ${nextRelease.version};
        sed -i 's%@version "[0-9\.]\+"%@version "${nextRelease.version}"%' mix.exs;
        sed -i 's%"~> [0-9\.]\+"},%"~> ${nextRelease.version}"},%' README.md;
      'publishCmd' : |
        echo pubhlish phoenix_react ${nextRelease.version};
        mix hex.publish --yes
